### ISSUE TITLE
TODO Before stable release

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/client-common#4]
- [x] Update email address
- [x] Update documentation link
- [x] Remove [unnecessary interface implementation](https://github.com/php-http/client-common/blob/master/src/Exception/BatchException.php#L16)
- [x] Remove composer stability config
- [x] Update composer dev alias
- [x] Update changelog
